#!/usr/bin/env python

# Script for the IUS project to create GitHub releases that correspond to when
# RPM packages are published to the testing and stable repositories.


import datetime
import pathlib

import click
import kitovu


default_timestamp = datetime.date.isoformat(datetime.date.today())
default_package = pathlib.Path.cwd().name


@click.group()
@click.pass_context
def cli(ctx):
    '''Release management tool.'''
    try:
        ctx.obj = kitovu.Api(profile='public')
    except kitovu.errors.MissingConfigError:
        raise SystemExit('no profile "public" found')


@click.command()
@click.pass_obj
@click.option('-p', '--package', default=default_package)
@click.option('-o', '--organization', default='iuscommunity-pkg')
@click.option('-d', '--debug', is_flag=True)
def list(api, package, organization, debug):
    '''List releases for a package.'''
    # GET /repos/:owner/:repo/releases
    uri = '/repos/{}/{}/releases'.format(organization, package)
    if debug:
        click.echo('GET {}'.format(uri))
    releases = api.get(uri).json()[0:3]
    for release in releases:
        status = 'testing' if release['prerelease'] else 'stable'
        click.echo('{} {}'.format(release['tag_name'], status))


@click.command()
@click.pass_obj
@click.argument('tag')
@click.option('-p', '--package', default=default_package)
@click.option('-o', '--organization', default='iuscommunity-pkg')
@click.option('-d', '--debug', is_flag=True)
def show(api, tag, package, organization, debug):
    '''Display details for a release.'''
    # GET /repos/:owner/:repo/releases/tags/:tag
    uri = '/repos/{}/{}/releases/tags/{}'.format(organization, package, tag)
    if debug:
        click.echo('GET {}'.format(uri))
    data = api.get(uri).json()
    #status = 'testing' if data['prerelease'] else 'stable'
    #click.echo('{} in {}'.format(data['tag_name'], status))
    click.echo('name: {}'.format(data['tag_name']))
    click.echo('prerelease: {}'.format(data['prerelease']))
    click.echo(data['body'])


@click.command()
@click.pass_obj
@click.argument('tag')
@click.option('-p', '--package', default=default_package)
@click.option('-o', '--organization', default='iuscommunity-pkg')
@click.option('-t', '--timestamp', default=default_timestamp)
@click.option('-d', '--debug', is_flag=True)
def testing(api, tag, package, organization, timestamp, debug):
    '''Create a testing release.'''
    # POST /repos/:owner/:repo/releases
    body = 'testing: {}'.format(timestamp)
    payload = {'tag_name': tag, 'name': tag, 'body': body, 'prerelease': True}
    uri = '/repos/{}/{}/releases'.format(organization, package)
    if debug:
        click.echo('POST {}'.format(uri))
        click.echo(payload)
    api.post(uri, payload)


@click.command()
@click.pass_obj
@click.argument('tag')
@click.option('-p', '--package', default=default_package)
@click.option('-o', '--organization', default='iuscommunity-pkg')
@click.option('-t', '--timestamp', default=default_timestamp)
@click.option('-d', '--debug', is_flag=True)
def stable(api, tag, package, organization, timestamp, debug):
    '''Create a stable release.'''
    # get current testing release
    # GET /repos/:owner/:repo/releases/tags/:tag
    uri = '/repos/{}/{}/releases/tags/{}'.format(organization, package, tag)
    if debug:
        click.echo('GET {}'.format(uri))
    data = api.get(uri).json()
    if not data['prerelease']:
        raise SystemExit('The current release is already marked "stable".')
    old_body = data['body']
    old_id = data['id']
    # delete current testing release
    # DELETE /repos/:owner/:repo/releases/:id
    uri = '/repos/{}/{}/releases/{}'.format(organization, package, old_id)
    if debug:
        click.echo('DELETE {}'.format(uri))
    api.delete(uri)
    # create new stable release
    # POST /repos/:owner/:repo/releases
    body = '{}\nstable: {}'.format(old_body, timestamp)
    payload = {'tag_name': tag, 'name': tag, 'body': body}
    uri = '/repos/{}/{}/releases'.format(organization, package)
    if debug:
        click.echo('POST {}'.format(uri))
        click.echo(payload)
    api.post(uri, payload)


cli.add_command(list)
cli.add_command(show)
cli.add_command(testing)
cli.add_command(stable)


if __name__ == '__main__':
    cli()


# vim: ft=python sw=4 ts=4 sts=4 et
